#!/usr/bin/env bash

fatal()
{
	echo "$1"
	exit 1
}

CMAKE_FLAGS="-B build"

if [ "$#" -gt 0 ]; then
	WINDOW_BACKEND="$1"
	WINDOW_BACKEND=${WINDOW_BACKEND^^}
	CMAKE_FLAGS=("$CMAKE_FLAGS" "-DWINDOW_BACKEND=$WINDOW_BACKEND")
fi

echo "Compiling shaders..."
./compile_shaders || fatal "Shader compilation failed!"
echo "Done!"

cmake "${CMAKE_FLAGS[@]}" || fatal "CMake error!"
make -C build/ || fatal "Make error!"

./build/VulkanTesting
