#!/bin/bash

WINDOW_BACKEND=${1:-"SDL"}
WINDOW_BACKEND=${WINDOW_BACKEND^^}

fatal()
{
	echo "$1"
	exit 1
}
 
echo "Compiling shaders..."
./compile_shaders || fatal "Shader compilation failed!"
echo "Done!"

cmake -DWINDOW_BACKEND="$WINDOW_BACKEND" -B build || fatal "CMake error!"
make -C build/ || fatal "Make error!"

./build/VulkanTesting
