#!/bin/bash

fatal()
{
	echo "$1"
	exit 1
}
 
echo "Compiling shaders..."
./compile_shaders || fatal "Shader compilation failed!"
echo "Done!"
cmake -B build || fatal "CMake error!"
make -C build/ || fatal "Make error!"

./build/VulkanTesting
